version: '3'
services:
  surreal:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./db-data:/db-data
    entrypoint:
      - /surreal
      - start
      - -b
      - 0.0.0.0:8000
      - --user
      - root
      - --pass
      - root
      - file:/db-data

  backend:
    image: ghcr.io/ixhbinphoenix/bne:latest
    env_file: ./backend/docker.env
    restart: unless-stopped # Needed for startup, 1st startup tries connecting to db before it's online
    network_mode: "host"
    volumes:
      - ./backend/key.pem:/key.pem
      - ./backend/cert.pem:/cert.pem
      - ./backend/email-templates/:/email-templates
