name: Clippy check
on:
  push:
    paths:
      - backend/**
      - flake.lock
      - flake.nix

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run clippy
        run: |
          cd backend
          nix develop -c cargo clippy --all-targets --all-features -- -Dwarnings

