name: Build docker container
on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'ixhbinphoenix/bne'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-action@main

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          nix build .
          docker image -i result
          docker push ghcr.io/ixhbinphoenix/bne:latest
