name: Build docker container
on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'ixhbinphoenix/bne'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: ghcr.io/ixhbinphoenix/bne:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
